-- Local development seed data.
--
-- UpgradR ships no demo/fixture rows here: every table is owner-scoped via
-- auth.users, and creating a realistic seed would require also seeding
-- auth.users (normally done through Supabase Auth, not plain SQL). Use the
-- app's sign-up flow (magic link) against the local stack to create a user,
-- then exercise the schema through the API.
--
-- Signing in without a browser: local Supabase routes ALL outbound mail to
-- Mailpit at http://127.0.0.1:54324 -- including messages addressed to real
-- external addresses, which are never actually delivered. A script or agent
-- can therefore request a magic link for any address, read it out of Mailpit,
-- and authenticate as that user. `npm run mcp:login -- --email you@example.com`
-- does exactly this; see docs/mcp.md, "Headless / scripted clients".
--
-- Database-level fixtures for automated testing live under
-- supabase/tests/database and create their own throwaway auth.users rows
-- inside a rolled-back transaction.
